name: doc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.6+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1

  # ✅ Freezed (runtime annotations only)
  freezed_annotation: ^3.1.0

  get_it: ^8.2.0

  # ✅ JSON (runtime annotations only)
  json_annotation: ^4.9.0

  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0

  intl: 0.20.2
  easy_localization: ^3.0.7
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.0.0
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  shimmer: ^3.0.0
  animated_bottom_navigation_bar: ^1.4.0
  iconsax: ^0.0.8
  easy_stepper: ^0.8.5+1
  easy_date_timeline: ^2.0.9
  font_awesome_flutter: ^10.8.0
  material_design_icons_flutter: ^7.0.7296
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  flutter_stripe: 12.1.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.5.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ✅ Code generators لازم تكون هنا
  build_runner: ^2.4.12
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - .env
